### ISSUE TITLE
New API Version

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/commerce_drupalgap_stripe#1]
Originally reported by @tennist here: https://github.com/signalpoint/DrupalGap/issues/886

I tried to create this issue on the Stripe Module repository, but it doesn't have an area to do so.

The stripe payment gateway has a new version of API than what is reported in the setup instructions for this DrupalGap module. The new Stipe API is used by the current Stripe Payment Gateway module in Drupal and it is not possible to have both API's on a single site. Step 3 of the setup instructions for the DrupalGap Module need to be updated to read version 3.23.0. The payment.inc file for the drupal module "Commerce DrupalGap Stripe also needs 3 revisions for the new Stripe API. The changes are as follows:

Line 31 needs to be changed to \Stripe\Stripe::setApiKey($settings['secret_key']);
Line 35 needs to be changed to 'source' => $data['stripe_token'],
Line 40 needs to be changed to $response = \Stripe\Charge::create($c);

I will also note these change requirements on the thread for the module as well.

**Comment by signalpoint** [comment]
I think I'll close this one in favor of this issue, since it has to do with the PHP side of things: https://www.drupal.org/node/2835639

**Comment by tennist** [comment]
I agree, but on the DrupalGap side of things, the setup instructions for this module need to be updated to reference the new version of the API.
